import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clicla Bikes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="bg-blue-400 w-32 h-32 rounded-full"></div>
        </div>
      </body>
    </html>
  );
}
